// <auto-generated />
using System;
using KurirServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KurirServer.Migrations
{
    [DbContext(typeof(KurirDbContext))]
    partial class KurirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KurirServer.Entities.Delivery", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourierID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<decimal>("DeliveryPrice");

                    b.Property<int>("DeliveryStatus");

                    b.Property<int>("DeliveryTypeID");

                    b.Property<string>("Description");

                    b.Property<int>("DispatcherID");

                    b.Property<int?>("EndAddressID");

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("PaymentTypeID");

                    b.Property<int?>("StartAddressID");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("UserID");

                    b.Property<int>("WaitingInMinutes");

                    b.HasKey("DeliveryID");

                    b.HasIndex("DeliveryTypeID");

                    b.HasIndex("EndAddressID");

                    b.HasIndex("PaymentTypeID");

                    b.HasIndex("StartAddressID");

                    b.HasIndex("UserID");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            DeliveryID = 1,
                            CourierID = 2,
                            CreateTime = new DateTime(2019, 9, 10, 12, 14, 0, 0, DateTimeKind.Unspecified),
                            DeliveryPrice = 160m,
                            DeliveryStatus = 0,
                            DeliveryTypeID = 1,
                            DispatcherID = 3,
                            EndAddressID = 2,
                            EndTime = new DateTime(2019, 10, 7, 21, 35, 3, 897, DateTimeKind.Local).AddTicks(287),
                            PaymentTypeID = 1,
                            StartAddressID = 1,
                            StartTime = new DateTime(2019, 9, 10, 12, 24, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1,
                            WaitingInMinutes = 0
                        },
                        new
                        {
                            DeliveryID = 2,
                            CourierID = 2,
                            CreateTime = new DateTime(2019, 9, 10, 12, 14, 0, 0, DateTimeKind.Unspecified),
                            DeliveryPrice = 160m,
                            DeliveryStatus = 0,
                            DeliveryTypeID = 1,
                            DispatcherID = 3,
                            EndAddressID = 2,
                            EndTime = new DateTime(2019, 10, 7, 21, 35, 3, 897, DateTimeKind.Local).AddTicks(3302),
                            PaymentTypeID = 2,
                            StartAddressID = 1,
                            StartTime = new DateTime(2019, 9, 10, 12, 24, 0, 0, DateTimeKind.Unspecified),
                            UserID = 1,
                            WaitingInMinutes = 0
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.DeliveryType", b =>
                {
                    b.Property<int>("DeliveryTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeliveryTypeName")
                        .IsRequired();

                    b.HasKey("DeliveryTypeID");

                    b.ToTable("DeliveryTypes");

                    b.HasData(
                        new
                        {
                            DeliveryTypeID = 1,
                            DeliveryTypeName = "Regular"
                        },
                        new
                        {
                            DeliveryTypeID = 2,
                            DeliveryTypeName = "Return shipping"
                        },
                        new
                        {
                            DeliveryTypeID = 3,
                            DeliveryTypeName = "Shoping"
                        },
                        new
                        {
                            DeliveryTypeID = 4,
                            DeliveryTypeName = "Post service"
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.FullAddress", b =>
                {
                    b.Property<int>("FullAddressID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("LocationID");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int?>("UserID");

                    b.Property<int>("Zone");

                    b.HasKey("FullAddressID");

                    b.HasIndex("LocationID");

                    b.HasIndex("UserID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            FullAddressID = 1,
                            Address = "Kosovska 1/2",
                            LocationID = 1,
                            Name = "Nikola",
                            Phone = "0612889085",
                            UserID = 1,
                            Zone = 1
                        },
                        new
                        {
                            FullAddressID = 2,
                            Address = "Temerinska 1/2",
                            LocationID = 1,
                            Name = "Marko",
                            Phone = "0612889085",
                            UserID = 1,
                            Zone = 1
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Altitude");

                    b.Property<DateTimeOffset>("DToffSet");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("UserID");

                    b.HasKey("LocationID");

                    b.HasIndex("UserID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            Altitude = 0.0,
                            DToffSet = new DateTimeOffset(new DateTime(1, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Latitude = 45.256872000000001,
                            Longitude = 19.849678999999998,
                            UserID = 0
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentTypeName");

                    b.HasKey("PaymentTypeID");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            PaymentTypeID = 1,
                            PaymentTypeName = "Kes"
                        },
                        new
                        {
                            PaymentTypeID = 2,
                            PaymentTypeName = "Preko racuna"
                        },
                        new
                        {
                            PaymentTypeID = 3,
                            PaymentTypeName = "Kupon"
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleID = 4,
                            RoleName = "Courier"
                        },
                        new
                        {
                            RoleID = 5,
                            RoleName = "Dispatcher"
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiveUserRoleID");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Mail")
                        .IsRequired();

                    b.Property<string>("Pass")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<int>("Procenat");

                    b.Property<DateTime>("RegistrationDate");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            ActiveUserRoleID = 0,
                            FirstName = "Default",
                            IsActive = false,
                            LastName = "eko",
                            Mail = "eko@eko.rs",
                            Pass = "eko",
                            Phone = "023771642",
                            Procenat = 0,
                            RegistrationDate = new DateTime(2019, 10, 7, 21, 35, 3, 881, DateTimeKind.Local).AddTicks(319)
                        },
                        new
                        {
                            UserID = 2,
                            ActiveUserRoleID = 0,
                            FirstName = "Max",
                            IsActive = false,
                            LastName = "Fast",
                            Mail = "max@gmail.com",
                            Pass = "lol",
                            Phone = "023771642",
                            Procenat = 60,
                            RegistrationDate = new DateTime(2019, 10, 7, 21, 35, 3, 893, DateTimeKind.Local).AddTicks(430)
                        },
                        new
                        {
                            UserID = 3,
                            ActiveUserRoleID = 0,
                            FirstName = "Matija",
                            IsActive = false,
                            LastName = "Levai",
                            Mail = "Matija@gmail.com",
                            Pass = "lol",
                            Phone = "023771642",
                            Procenat = 70,
                            RegistrationDate = new DateTime(2019, 10, 7, 21, 35, 3, 893, DateTimeKind.Local).AddTicks(1243)
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleID");

                    b.Property<int>("UserID");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleID = 1,
                            RoleID = 1,
                            UserID = 3
                        },
                        new
                        {
                            UserRoleID = 2,
                            RoleID = 2,
                            UserID = 3
                        },
                        new
                        {
                            UserRoleID = 3,
                            RoleID = 3,
                            UserID = 3
                        },
                        new
                        {
                            UserRoleID = 4,
                            RoleID = 4,
                            UserID = 3
                        },
                        new
                        {
                            UserRoleID = 5,
                            RoleID = 5,
                            UserID = 3
                        },
                        new
                        {
                            UserRoleID = 6,
                            RoleID = 3,
                            UserID = 1
                        },
                        new
                        {
                            UserRoleID = 7,
                            RoleID = 3,
                            UserID = 2
                        },
                        new
                        {
                            UserRoleID = 8,
                            RoleID = 4,
                            UserID = 2
                        },
                        new
                        {
                            UserRoleID = 9,
                            RoleID = 5,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("KurirServer.Entities.Delivery", b =>
                {
                    b.HasOne("KurirServer.Entities.DeliveryType", "DeliveryType")
                        .WithMany()
                        .HasForeignKey("DeliveryTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KurirServer.Entities.FullAddress", "EndAddress")
                        .WithMany()
                        .HasForeignKey("EndAddressID");

                    b.HasOne("KurirServer.Entities.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KurirServer.Entities.FullAddress", "StartAddress")
                        .WithMany()
                        .HasForeignKey("StartAddressID");

                    b.HasOne("KurirServer.Entities.User")
                        .WithMany("UsersDeliveries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KurirServer.Entities.FullAddress", b =>
                {
                    b.HasOne("KurirServer.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("KurirServer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("KurirServer.Entities.Location", b =>
                {
                    b.HasOne("KurirServer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KurirServer.Entities.UserRole", b =>
                {
                    b.HasOne("KurirServer.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KurirServer.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
